# PHASE 4 PROJECT : GROUP 10.

# Project Title: Time Series Modelling of Real Estate Value.

# Team Members ;

1.Joan Nyamache

2.Marion Achieng

3.Eugene Marius

# Introduction

Zillow is a real estate company that provides extensive datasets that offer insights into the housing market.The stakeholder in this project is seeking to construct residential homes in the United States that provide a return on investment.
This project aims to construct a time series model leveraging Zillow's dataset to assist real estate investors in making well-informed investment decisions.

# Overview

In this project we aim to do the following:

Loading the dataset.

* Gaining a comprehensive understanding of the dataset.

* Identifying and selecting our target variable.

* Preparing the dataset, which involves tasks such as cleaning, checking for multicollinearity, and ensuring data integrity.

* Encoding categorical variables to make them compatible with our modeling process.

* Evaluating the performance of our models using appropriate metrics.

* Utilizing our trained models for making predictions.

* Drawing meaningful insights and conclusions based on our findings.

# Business understanding

The world of real estate investing is a dynamic and lucrative field, requiring careful research and well-planned choices. A fictional company specializing in real estate investments is seeking valuable information to identify the five most promising postal codes (zip codes) for future ventures. To achieve this goal, we'll utilize historical data provided by Zillow Research.

# Problem Statement

The driving force behind this project is a real estate development company in the United States. Their primary objective is to construct residential properties that offer a significant financial return.

To achieve this goal, we'll be conducting a time series analysis on historical housing data from Zillow. This data encompasses various locations across the country. By analyzing these trends, we aim to pinpoint the most promising areas for investment, allowing the company to build homes with high profit potential.

# Objectives

1. Identify the top 5 zip codes for the real estate agency to invest in.

2. Forecast future house prices in these zip codes.

3. Provide insights and recommendations

# Data Understanding

The dataset used in this project comprises historical median house prices from various states in the USA, spanning from April 1996 to April 2018 (22 years). This data was obtained from the Zillow website.

The dataset contains 14,723 rows and 272 columns, with 4 categorical columns and 268 numerical columns.
The dataset encompasses details on a range of attributes, including RegionID, RegionName, City, State, Metro, SizeRank, CountyName, and the value representing real estate prices

Data Preparation

Lets import the reevent libraries ;

In [4]:
#Importing the data libraries
import numpy as np
import pandas as pd
import itertools
import warnings
warnings.filterwarnings('ignore')

#importing visualisation libraries
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

#Importing modeling libraries
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.graphics.tsaplots import plot_pacf
from matplotlib.pylab import rcParams
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error, mean_absolute_error
import joblib

In [10]:
#preview the first 5 columns of the data set
data = pd.read_csv('zillow_data.csv')
df = data.copy()
df.head()

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04
0,84654,60657,Chicago,IL,Chicago,Cook,1,334200.0,335400.0,336500.0,...,1005500,1007500,1007800,1009600,1013300,1018700,1024400,1030700,1033800,1030600
1,90668,75070,McKinney,TX,Dallas-Fort Worth,Collin,2,235700.0,236900.0,236700.0,...,308000,310000,312500,314100,315000,316600,318100,319600,321100,321800
2,91982,77494,Katy,TX,Houston,Harris,3,210400.0,212200.0,212200.0,...,321000,320600,320200,320400,320800,321200,321200,323000,326900,329900
3,84616,60614,Chicago,IL,Chicago,Cook,4,498100.0,500900.0,503100.0,...,1289800,1287700,1287400,1291500,1296600,1299000,1302700,1306400,1308500,1307000
4,93144,79936,El Paso,TX,El Paso,El Paso,5,77300.0,77300.0,77300.0,...,119100,119400,120000,120300,120300,120300,120300,120500,121000,121500

In [11]:
# preview the last five columns of the dataset
df.tail()

,RegionID,RegionName,City,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,...,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04
14718,58333,1338,Ashfield,MA,Greenfield Town,Franklin,14719,94600.0,94300.0,94000.0,...,216800,217700,218600,218500,218100,216400,213100,209800,209200,209300
14719,59107,3293,Woodstock,NH,Claremont,Grafton,14720,92700.0,92500.0,92400.0,...,202100,208400,212200,215200,214300,213100,213700,218300,222700,225800
14720,75672,40404,Berea,KY,Richmond,Madison,14721,57100.0,57300.0,57500.0,...,121800,122800,124600,126700,128800,130600,131700,132500,133000,133400
14721,93733,81225,Mount Crested Butte,CO,NaN,Gunnison,14722,191100.0,192400.0,193700.0,...,662800,671200,682400,695600,695500,694700,706400,705300,681500,664400
14722,95851,89155,Mesquite,NV,Las Vegas,Clark,14723,176400.0,176300.0,176100.0,...,333800,336400,339700,343800,346800,348900,350400,353000,356000,357200

In [12]:
#view the column names
df.columns

Index(['RegionID', 'RegionName', 'City', 'State', 'Metro', 'CountyName',
       'SizeRank', '1996-04', '1996-05', '1996-06',
       ...
       '2017-07', '2017-08', '2017-09', '2017-10', '2017-11', '2017-12',
       '2018-01', '2018-02', '2018-03', '2018-04'],
      dtype='object', length=272)

In [14]:
# Lets rename the regionmane to zipcode because it contains the zipcode data
df = df.rename(columns={'RegionName': 'Zipcode'})

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14723 entries, 0 to 14722
Columns: 272 entries, RegionID to 2018-04
dtypes: float64(219), int64(49), object(4)
memory usage: 30.6+ MB

In [17]:
#checking for duplicates
df.duplicated().sum()

0

In [19]:
df.describe

<bound method NDFrame.describe of        RegionID  Zipcode                 City State              Metro  \
0         84654    60657              Chicago    IL            Chicago
1         90668    75070             McKinney    TX  Dallas-Fort Worth
2         91982    77494                 Katy    TX            Houston
3         84616    60614              Chicago    IL            Chicago
4         93144    79936              El Paso    TX            El Paso
...         ...      ...                  ...   ...                ...
14718     58333     1338             Ashfield    MA    Greenfield Town
14719     59107     3293            Woodstock    NH          Claremont
14720     75672    40404                Berea    KY           Richmond
14721     93733    81225  Mount Crested Butte    CO                NaN
14722     95851    89155             Mesquite    NV          Las Vegas

      CountyName  SizeRank   1996-04   1996-05   1996-06  ...  2017-07  \
0           Cook         1  334200.0  335400.0  336500.0  ...  1005500
1         Collin         2  235700.0  236900.0  236700.0  ...   308000
2         Harris         3  210400.0  212200.0  212200.0  ...   321000
3           Cook         4  498100.0  500900.0  503100.0  ...  1289800
4        El Paso         5   77300.0   77300.0   77300.0  ...   119100
...          ...       ...       ...       ...       ...  ...      ...
14718   Franklin     14719   94600.0   94300.0   94000.0  ...   216800
14719    Grafton     14720   92700.0   92500.0   92400.0  ...   202100
14720    Madison     14721   57100.0   57300.0   57500.0  ...   121800
14721   Gunnison     14722  191100.0  192400.0  193700.0  ...   662800
14722      Clark     14723  176400.0  176300.0  176100.0  ...   333800

       2017-08  2017-09  2017-10  2017-11  2017-12  2018-01  2018-02  2018-03  \
0      1007500  1007800  1009600  1013300  1018700  1024400  1030700  1033800
1       310000   312500   314100   315000   316600   318100   319600   321100
2       320600   320200   320400   320800   321200   321200   323000   326900
3      1287700  1287400  1291500  1296600  1299000  1302700  1306400  1308500
4       119400   120000   120300   120300   120300   120300   120500   121000
...        ...      ...      ...      ...      ...      ...      ...      ...
14718   217700   218600   218500   218100   216400   213100   209800   209200
14719   208400   212200   215200   214300   213100   213700   218300   222700
14720   122800   124600   126700   128800   130600   131700   132500   133000
14721   671200   682400   695600   695500   694700   706400   705300   681500
14722   336400   339700   343800   346800   348900   350400   353000   356000

       2018-04
0      1030600
1       321800
2       329900
3      1307000
4       121500
...        ...
14718   209300
14719   225800
14720   133400
14721   664400
14722   357200

[14723 rows x 272 columns]>

In [18]:
#checking for missing values
df.isna().sum()

RegionID       0
Zipcode        0
City           0
State          0
Metro       1043
            ...
2017-12        0
2018-01        0
2018-02        0
2018-03        0
2018-04        0
Length: 272, dtype: int64

In [20]:
# Remove rows with missing values (NaN) 
df.dropna(inplace = True)

In [21]:
df.isna().sum()

RegionID    0
Zipcode     0
City        0
State       0
Metro       0
           ..
2017-12     0
2018-01     0
2018-02     0
2018-03     0
2018-04     0
Length: 272, dtype: int64